[package]
name = "plain-text-accounting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
nom = "7.1.3"
rust_decimal = "1.35.0"
